apps:
  # List of 3rd party apt repos to add.
  repos:
    google-chrome:
      repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      gpg: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
    sublime:
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      gpg: 'https://download.sublimetext.com/sublimehq-pub.gpg'

  # List of *.deb URLs to install.
  deb:
   - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
   - https://download.xnview.com/XnViewMP-linux-x64.deb
   - https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
   - https://downloads.slack-edge.com/releases/linux/4.18.0/prod/x64/slack-desktop-4.18.0-amd64.deb
   - https://global.download.synology.com/download/Utility/SynologyDriveClient/3.0.1-12674/Ubuntu/Installer/x86_64/synology-drive-client-12674.x86_64.deb
   - https://zoom.us/client/latest/zoom_amd64.deb
   #- https://repo.skype.com/latest/skypeforlinux-64.deb

  # List of apt packages to install.
  apt:
    ###> System/CLI apps
    - cifs-utils  # Common Internet File System utilities
    - curl        # Command line tool for transferring data with URL syntax
    - default-jdk # Jave development kit
    - default-jre # Java runtime
    - exfat-fuse  # Read and write exFAT driver
    - exfat-utils # Utilities to create, check, label and dump exFAT file system
    - git
    - git-flow
    - grub-customizer  # GUI for GRUB settings management
    - heif-gdk-pixbuf  # Apple HEIF/HEIC decoder support 
    - heif-thumbnailer # Apple HEIF/HEIC thumbnails support 
    - htop        # Terminal system monitor
    - jq          # Takes JSON input and retrieves data by query
    - mc          # Two panel terminal file manager
    - neofetch    # Shows Linux System Information with Distribution Logo
    - net-tools   # Base network tools
    - nfs-common  # Package for work with NFS shares
    - openfortivpn # Corporate VPN open source alternative.
    - stacer      # Cool CleanMyMac alternative
    - traceroute  # Traces the route taken by packets over an IPv4/IPv6 network
    - tree        # Displays an indented directory tree, in color
  
    ###> Archive formats support
    - arj         # arj archiver
    - lhasa       # lzh unarchiver
    - rar         # rar archiver
    - unrar       # rar unarchiver
    - unzip       # zip unarchiver
    - zip         # zip archiver

    ###> Office
    - libreoffice
    - libreoffice-base-drivers # Base drivers
    - libreoffice-help-en-us   # Help: English
    - libreoffice-help-ru      # Help: Russian
    - libreoffice-l10n-ru      # Localization: Russian
    - libreoffice-l10n-uk      # Localization: Ukrainian

    ###> Web browsers
    - firefox              # From Mozilla team with <3
    - google-chrome-stable # Thing for collecting your personal data

    ###> Media/Internet/Office
    - clementine           # Audio/Radio/Podcasts player
    - dia                  # Diagram editor
    - evolution            # Outlook alternative
    - evolution-ews        # Evolution Exchange support
    - ffmpeg               # Universal media transcoder tool
    - flameshot            # Screenshot tool
    - inkscape             # Vector image editor
    - transmission         # Torrent client
    - vlc                  # Legend!

    ###> Developer tools
    - sublime-merge        # Git GUI
    - sublime-text         # Text/code editor

    ###> Gnome-based distro packages.
    # - gnome-tweaks
    # - network-manager-openvpn
    # - network-manager-openvpn-gnome

    ###> KDE apps
    #- kompare  # File difference viewer
    #- krename  # Batch renamer for KDE
    #- krusader # Two-panel file manager
    #- okular   # Universal document viewer
    #- yakuake  # Quake-style dropdown terminal

  flatpak:
    - com.getpostman.Postman # API debugging tool
    - com.github.johnfactotum.Foliate # eBook reader
    - com.viber.Viber # Viber messanger
    - org.telegram.desktop # Best IM!
    # - com.discordapp.Discord
    # - com.rafaelmardojai.Blanket # Listen to different sounds
    # - com.spotify.Client

docker:
  install: yes
  docksal:
    install: yes
    settings:
      DOCKSAL_CONTAINER_HEALTHCHECK_INTERVAL: 10s # Throttle healthchecks for less syslog entries.
      DOCKSAL_DNS_DISABLED: 0 # Set 1 for disable docksal DNS container at all.
      DOCKSAL_DNS_UPSTREAM: 1.1.1.1 # Use CloudFlare DNS as its faster than google's DNS.

php:
  install: yes
  version: 7.4
  # @TODO: Add composer version select: v1 or v2.
  composer:
    # List of global composer packages to install.
    #
    # NOTE: All the following packages will be installed using `consolidation/cgr`.
    global:
      - drush/drush
      - squizlabs/php_codesniffer
      - drupal/coder              # PHPCS Drupal standards
      - friendsofphp/php-cs-fixer # PHPCS standard fixer
      - mglaman/drupal-check      # Drupal static code analysis tool

node:
  install: yes
  # List of node versions to install.
  versions: 
    - 14
    - 12
    - 10
  defaultVersion: node # Latest installed node version.
  npm:
    # List of global npm packages to install for default node.
    global: 
      - bower
      - eslint
      - eslint-config-airbnb
      - eslint-config-google
      - eslint-config-standard
      - eslint-plugin-import
      - eslint-plugin-jsx-a11y
      - eslint-plugin-node
      - eslint-plugin-promise
      - eslint-plugin-react
      - eslint-plugin-react-hooks
      - firebase-tools
      - flow
      - flow-bin
      - gulp
      - http-server
      - lsp
      - snyk
      - typescript
      - vscode-css-languageserver-bin
      - vscode-html-languageserver-bin
      - yarn

python:
  install: yes
  version: 3.9
  pip3:
    # List of global packages to install.
    global:
      - click # Handy-dandy module for writing terminal apps.
      - feedparser # RSS parser.
      - ffmpeg-normalize # Normalizes audio using ffmpeg.
      - ffpb # ffmpeg with progress bar.
      - yq # Takes YAML input and retrieves data by query.

vscode:
  install: yes
  # List of plugins to install.
  extensions:
    - amazonwebservices.aws-toolkit-vscode # AWS toolkit
    - acarreiro.calculate                # Calculates inline math expr
    - christian-kohler.path-intellisense # File path autocomplete
    - coenraads.bracket-pair-colorizer   # Bracket Pair Colorizer
    - dakara.transformer                 # Filter, Sort, Unique, Reverse, Align, CSV, Line Selection, Text Transformations and Macros
    - editorconfig.editorconfig          # EditorConfig support
    - esbenp.prettier-vscode             # Prettier - Code formatter
    - github.github-vscode-theme         # GitHub color theme
    - golang.go                          # Golang support
    - hookyqr.beautify                   # HTML/JSON beautifier
    - mhutchie.git-graph                 # Git graph
    - mikestead.dotenv                   # .env support
    - ms-azuretools.vscode-docker        # Docker support
    - ms-python.python                   # Python support
    - ms-vscode-remote.remote-ssh        # SSH support 
    - pkief.material-icon-theme          # Material Icon Theme
    #- TabNine.tabnine-vscode            # AI-assisted autocomplete
    - tyriar.lorem-ipsum                 # Lorem Ipsum generator
    - tommasov.hosts                     # Hosts file syntax highlighter.
    - william-voyek.vscode-nginx         # nginx.conf support
    - yzhang.markdown-all-in-one         # Markdown tools
    #- alefragnani.Bookmarks             # Bookmarks

    # Node/NPM/Yarn specific extensions
    - christian-kohler.npm-intellisense # NPM better autocomplete
    - dbaeumer.vscode-eslint            # Eslint support
    - mariusschulz.yarn-lock-syntax     # yarn.lock syntax highlight
    # PHP/Drupal specific extensions
    - ikappas.composer         # Composer support
    - ikappas.phpcs            # PHP CodeSniffer

jetbrains:
  toolbox:
    install: yes

cloud:
  aws: # AWS CLI v2
    install: yes
  gcloud:
    install: yes
    packages:
      - google-cloud-sdk
      - google-cloud-sdk-minikube
      - kubectl
