# Fish shell.
fish:
  install: true
  set_default: true
  theme: lambda
  packages:
    - https://github.com/edc/bass
    - https://github.com/derekstavis/plugin-nvm
    - https://github.com/oh-my-fish/plugin-aws
    - https://github.com/evanlucas/fish-kubectl-completions

#### Languages and interpreters. ###############################################
python3:
  install: true
  pip3_global_packages:
    - awsebcli         # AWS Elastic Beanstalk CLI. 
    - click            # Handy-dandy module for writing terminal apps.
    - feedparser       # RSS parser.
    - ffmpeg-normalize # Normalizes audio using ffmpeg.
    - ffpb             # ffmpeg with progress bar.
    - yq               # Takes YAML input and retrieves data by query.
    - yt-dlp           # Advanced fork of youtube-dl.

php:
  install: true
  composer_global_packages:
    - drush/drush
    - squizlabs/php_codesniffer
    #- drupal/coder              # PHPCS Drupal standards
    #- friendsofphp/php-cs-fixer # PHPCS standard fixer

node:
  install: true
  version: 18 # LTS
  npm_global_packages: 
    - '@nestjs/cli' # Nest.JS CLI
    - contentful-cli # Contentful.com CLI
    - dynamodb-admin # Handy Web-UI for viewing local DynamoDB data
    - eslint
    - eslint-config-airbnb
    - eslint-config-google
    - eslint-config-standard
    - eslint-plugin-import
    - eslint-plugin-jsx-a11y
    - eslint-plugin-node
    - eslint-plugin-promise
    - eslint-plugin-react
    - eslint-plugin-react-hooks
    - firebase-tools
    - flow
    - flow-bin
    - gulp
    - http-server # Simple HTTP server for static files in directory
    - lsp
    - snyk # snyk.com CLI
    - typescript
    - vscode-css-languageserver-bin
    - vscode-html-languageserver-bin

#### Cloud tools and utils. ####################################################
cloud:
  # AWS CLI v2
  aws_cli:
    install: true

  # Google Cloud SDK
  gcloud: 
    install: true
    version: '367.0.0'
    components:
      - cloud-datastore-emulator
      - cloud-firestore-emulator
      - pubsub-emulator
      - cloud-build-local
      - kubectl
      - minikube

  # HashiCorp Terraform
  terraform:
    install: true

#### Docker things. ############################################################
# Docker Community Edition
docker:
  install: true

# Docker Compose-based all-purpose web-development environment.
# @see https://docksal.io/
docksal:
  install: true
  config:
    DOCKSAL_CONTAINER_HEALTHCHECK_INTERVAL: 10s # Throttle healthchecks for less syslog entries.
    DOCKSAL_DNS_DISABLED: 0 # Set 1 for disable docksal DNS container at all.
    DOCKSAL_DNS_UPSTREAM: 1.1.1.1 # Use CloudFlare DNS as its faster than google's DNS.

#### Applications and packages #################################################
apps:
  jetbrains_toolbox:
    install: true

  visual_studio_code:
    install: true
    extensions:
      - acarreiro.calculate                  # Calculates inline math expr
      - amazonwebservices.aws-toolkit-vscode # AWS toolkit
      - christian-kohler.path-intellisense   # File path autocomplete
      - dakara.transformer                   # Filter, Sort, Unique, Reverse, Align, CSV, Line Selection, Text Transformations and Macros
      - editorconfig.editorconfig            # EditorConfig support
      - esbenp.prettier-vscode               # Prettier - Code formatter
      - GitHub.copilot                       # GitHub Copilot!
      - golang.go                            # Golang support
      - hookyqr.beautify                     # HTML/JSON beautifier
      - LeetCode.vscode-leetcode             # Leetcode.com plugin
      - mhutchie.git-graph                   # Git graph
      - mikestead.dotenv                     # .env support
      - ms-azuretools.vscode-docker          # Docker support
      - ms-python.python                     # Python support
      - ms-vscode-remote.remote-ssh          # SSH support 
      - redhat.ansible                       # Ansible support
      - tommasov.hosts                       # Hosts file syntax highlighter
      - tyriar.lorem-ipsum                   # Lorem Ipsum generator
      - william-voyek.vscode-nginx           # nginx.conf support
      - yzhang.markdown-all-in-one           # Markdown tools
      #- alefragnani.Bookmarks               # Bookmarks
      #- TabNine.tabnine-vscode              # AI-assisted autocomplete
    
      # Node/NPM/Yarn specific extensions
      - christian-kohler.npm-intellisense # NPM better autocomplete
      - dbaeumer.vscode-eslint            # Eslint support
      - mariusschulz.yarn-lock-syntax     # yarn.lock syntax highlight

      # PHP/Drupal specific extensions
      - ikappas.composer # Composer support
      - ikappas.phpcs    # PHP CodeSniffer

      # Themes
      - github.github-vscode-theme    # GitHub color theme
      - pkief.material-icon-theme     # Material Icon Theme
      - rokoroku.vscode-theme-darcula # JetBrains-like theme

  ### Flatpak's apps (using flathub.org repo)
  flatpak:
    - app.resp.RESP # Redis GUI client
    - com.discordapp.Discord
    - com.getpostman.Postman # API debugging tool
    - com.github.johnfactotum.Foliate # eBook reader
    - com.slack.Slack
    - com.synology.SynologyDrive # Synology Drive Client
    - com.xnview.XnViewMP
    - org.flameshot.Flameshot # Screenshot tool. @TODO: Replace with Deepin Screenshot.
    - org.remmina.Remmina # Remote desktop client (RDP, VNC)
    #- org.telegram.desktop # Best IM!
    - us.zoom.Zoom
    # - com.microsoft.Teams
    # - com.rafaelmardojai.Blanket # Listen to different sounds
    # - com.skype.Client
    # - com.spotify.Client
    # - com.viber.Viber # Viber messanger

  # List of *.deb URLs that needs to be installed.
  deb_urls:
    1password: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    google-chrome: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #teamviewer: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    # zoom: https://zoom.us/client/latest/zoom_amd64.deb # Use Flatpak version instead for better stability.

  # List of packages that needs to be installed.
  # Check all the packages are available in your repos before running playbook.
  packages:
    ### System/CLI apps
    - apache2-utils # Apache utils. Provides 'ab' command.
    - cifs-utils  # Common Internet File System utilities
    - curl        # Command line tool for transferring data with URL syntax
    - default-jdk # Java development kit
    - deja-dup    # System backup tool
    - default-jre # Java runtime
    - git         # You know what it is.
    - git-flow    # High-level git repository actions helper.
    - heif-gdk-pixbuf  # Apple HEIF/HEIC decoder support
    - heif-thumbnailer # Apple HEIF/HEIC thumbnails support
    - htop        # Terminal system monitor
    - jq          # Takes JSON input and retrieves data by query
    - mc          # Two panel terminal file manager
    - neofetch    # Shows Linux System Information with Distribution Logo
    - net-tools   # Base network tools
    - nfs-common  # Package for work with NFS shares
    - openfortivpn # Corporate VPN open source alternative.
    - stacer      # Cool CleanMyMac alternative
    - tldr        # Displays simple help pages for command-line tools.
    - traceroute  # Traces the route taken by packets over an IPv4/IPv6 network
    - tree        # Displays an indented directory tree, in color
    ### Archive formats support
    - p7zip-full  # 7z and 7za file archivers with high compression ratio
    - zip         # zip archiver
    ### Office
    - libreoffice
    - libreoffice-base-drivers # Base drivers
    - libreoffice-help-en-us   # Help: English
    - libreoffice-help-ru      # Help: Russian
    - libreoffice-l10n-ru      # Localization: Russian
    - libreoffice-l10n-uk      # Localization: Ukrainian
    ### Media/Internet/Office
    - clementine             # Audio/Radio/Podcasts player
    - dia                    # Diagram editor
    - evolution              # Outlook alternative
    - evolution-ews          # Evolution Exchange support
    - ffmpeg                 # Universal media transcoder tool
    - inkscape               # Vector image editor
    - transmission           # Torrent client
    - vlc                    # Legend!
    #- deepin-screen-recorder # Record desktop video.
    #- deepin-screenshot      # Screenshot tool.
    ### Gnome-based distro packages.
    # - gnome-tweaks
    # - network-manager-openvpn
    # - network-manager-openvpn-gnome
    ### KDE apps
    #- kompare  # File difference viewer
    #- krename  # Batch renamer for KDE
    #- krusader # Two-panel file manager
    #- okular   # Universal document viewer
    #- yakuake  # Quake-style dropdown terminal

#### Google fonts to install ###################################################
google_fonts:
  install: true
  fonts_dir: '{{ ansible_env.HOME }}/.fonts'
  fonts_list:
    #- jetbrains-mono
    - open-sans
    - ubuntu
    - ubuntu-mono
