---

roles:
  - name: aws-cli
    src: deekayen.awscli2

  - name: docker
    src: https://github.com/haxorof/ansible-role-docker-ce

  - name: docksal
    src: https://github.com/alexander-danilenko/ansible-role-docksal

  - name: google-cloud-sdk
    src: markosamuli.gcloud

  - name: jetbrains-toolbox
    src: https://github.com/jaredhocutt/ansible-jetbrains-toolbox

  - name: visual-studio-code
    src: gantsign.visual-studio-code

  - name: zsh
    src: https://github.com/alexander-danilenko/ansible-role-zsh-antigen
