galaxy_info:
  author: Alexander Danilenko
  description: Install Node Version Manager, certain Node version and global npm packages.
  company: FFW Agency
  license: MIT

  min_ansible_version: 2.9

  platforms:
  - name: Fedora
    versions:
      - all
  - name: Debian
    versions:
      - all
  - name: Ubuntu
    versions:
      - all
  galaxy_tags: []

dependencies: []
