- name: '*.deb tasks'
  include_tasks: 'deb.yml'

- name: 'Install packages for current distro'
  become: yes
  package:
    name: '{{ apps_packages }}'
    state: 'present'
    use: 'auto' # Automatically detect current package manager.

- name: 'Flatpak tasks'
  when: apps_flatpak_packages | length > 0
  include_tasks: 'flatpak.yml'
