galaxy_info:
  author: Alexander Danilenko
  description: Installs zsh + antigen and sets zsh as a default shell
  company: FFW Agency
  license: MIT

  min_ansible_version: 2.9

  platforms:
  - name: Fedora
    versions:
      - all
  - name: Debian
    versions:
      - all
  - name: Ubuntu
    versions:
      - all
  galaxy_tags: []

dependencies: []
